### ISSUE TITLE
Update Kurono Student Challenge 3

### ISSUE THREAD

**Issue by razvan-pro** [ocadotechnology/codeforlife-teaching-resources#18]
We need to add to the worksheet that students need to check that the list is not empty before trying to use it. (The list can be empty if there are no nearby artefacts)

![image.png](https://images.zenhubusercontent.com/5f85c3d6e2d1743292fdea34/3d7c63c3-92ea-438e-84e6-aa0689062e4f)

**Comment by SKairinos** [comment]
taking aimmo offline
