### ISSUE TITLE
Update worksheet 2 to include backpack

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-teaching-resources#8]
Now that we are implementing the backpack concept, this replaces the `number_of_artefacts` attribute.

## Acceptance Criteria
- [x] Backpack concept is introduced in worksheet 2
- [x] `number_of_artefacts` is replaced with `len(backpack)`
- [x] "Pickup ten artefacts" at the end of the worksheet is changed to pick up one

**Comment by mrniket** [comment]
In the summary for Student Challenge 2: 

>Well done! You have done a lot this session. You have found out how to avoid obstacles and influence which way your avatar moves. You have also learned how to pick up artefacts and manage your inventory.

should we say manage your backpack?

Also:

> You can check how many artefacts you have picked up at any time using this code:

Should we elaborate on this part and talk about the backpack more?

**Comment by faucomte97** [comment]
I made the above changes and also updated the teacher worksheet 2 to reflect those changes

**Comment by mrniket** [comment]
- [ ] The last example solutions in teacher worksheet 2 still need to be updated

Looks good though, should we also say how to look inside what's in your backpack (i.e. `print(avatar_state.backpack)`) or is that purposely left for worksheet 3?

**Comment by faucomte97** [comment]
Done :)
